# Running code concurrently using threading ...

In [1]:
import requests
import time
import concurrent.futures

img_urls = [
    'https://images.unsplash.com/photo-1516117172878-fd2c41f4a759',
    'https://images.unsplash.com/photo-1532009324734-20a7a5813719',
    'https://images.unsplash.com/photo-1524429656589-6633a470097c',
    'https://images.unsplash.com/photo-1530224264768-7ff8c1789d79',
    'https://images.unsplash.com/photo-1564135624576-c5c88640f235',
    'https://images.unsplash.com/photo-1541698444083-023c97d3f4b6',
    'https://images.unsplash.com/photo-1522364723953-452d3431c267',
    'https://images.unsplash.com/photo-1513938709626-033611b8cc03',
    'https://images.unsplash.com/photo-1507143550189-fed454f93097',
    'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
    'https://images.unsplash.com/photo-1504198453319-5ce911bafcde',
    'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99',
    'https://images.unsplash.com/photo-1516972810927-80185027ca84',
    'https://images.unsplash.com/photo-1550439062-609e1531270e',
    'https://images.unsplash.com/photo-1549692520-acc6669e2f0c'
]

t1 = time.perf_counter()


def download_image(img_url):
    img_bytes = requests.get(img_url).content
    img_name = img_url.split('/')[3]
    img_name = f'{img_name}.jpg'
    with open(img_name, 'wb') as img_file:
        img_file.write(img_bytes)
        print(f'{img_name} was downloaded...')


with concurrent.futures.ThreadPoolExecutor() as executor:
    executor.map(download_image, img_urls)


t2 = time.perf_counter()

print(f'Finished in {t2-t1} seconds')

photo-1564135624576-c5c88640f235.jpg was downloaded...
photo-1549692520-acc6669e2f0c.jpg was downloaded...
photo-1530224264768-7ff8c1789d79.jpg was downloaded...
photo-1532009324734-20a7a5813719.jpg was downloaded...
photo-1522364723953-452d3431c267.jpg was downloaded...
photo-1516117172878-fd2c41f4a759.jpg was downloaded...
photo-1507143550189-fed454f93097.jpg was downloaded...
photo-1516972810927-80185027ca84.jpg was downloaded...
photo-1504198453319-5ce911bafcde.jpg was downloaded...
photo-1550439062-609e1531270e.jpg was downloaded...
photo-1530122037265-a5f1f91d3b99.jpg was downloaded...
photo-1513938709626-033611b8cc03.jpg was downloaded...
photo-1524429656589-6633a470097c.jpg was downloaded...
photo-1541698444083-023c97d3f4b6.jpg was downloaded...
photo-1493976040374-85c8e12f0c0e.jpg was downloaded...
Finished in 137.270769632 seconds


# MultiProcessing Concept (running code in Parallel)...

In [ ]:
import requests
import time
import concurrent.futures
import multiprocessing

img_urls = [
    'https://images.unsplash.com/photo-1516117172878-fd2c41f4a759',
    'https://images.unsplash.com/photo-1532009324734-20a7a5813719',
    'https://images.unsplash.com/photo-1524429656589-6633a470097c',
    'https://images.unsplash.com/photo-1530224264768-7ff8c1789d79',
    'https://images.unsplash.com/photo-1564135624576-c5c88640f235',
    'https://images.unsplash.com/photo-1541698444083-023c97d3f4b6',
    'https://images.unsplash.com/photo-1522364723953-452d3431c267',
    'https://images.unsplash.com/photo-1513938709626-033611b8cc03',
    'https://images.unsplash.com/photo-1507143550189-fed454f93097',
    'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e',
    'https://images.unsplash.com/photo-1504198453319-5ce911bafcde',
    'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99',
    'https://images.unsplash.com/photo-1516972810927-80185027ca84',
    'https://images.unsplash.com/photo-1550439062-609e1531270e',
    'https://images.unsplash.com/photo-1549692520-acc6669e2f0c'
]

t1 = time.perf_counter()


def download_image(img_url):
    img_bytes = requests.get(img_url).content
    img_name = img_url.split('/')[3]
    img_name = f'{img_name}.jpg'
    with open(img_name, 'wb') as img_file:
        img_file.write(img_bytes)
        return f'{img_name} was downloaded...'

#context manager concept        
with concurrent.futures.ProcessPoolExecutor() as executor:
    """
    #METHOD-2 (took 12.9 secs) submit task as per sequence and return as per whoever completed first.
    results = [executor.submit(download_image, img_url) for img_url in img_urls]
    for f in concurrent.futures.as_completed(results):
        print(f.result())
    """
    
    #"""
    #METHOD-3 (using python build in map method) # (took 13.5 secs)
    # submit task as per sequence and return as per the same sequence.
    results = executor.map(download_image, img_urls) # this doesn't return process object as like METHOD-2 but return result instaed.
    for result in results:
        print(result)
    #"""
    
        
"""
#METHOD-1 (took 13.41 secs)
processess = []
for i in range(len(img_urls)):
    p = multiprocessing.Process(target=download_image, args=[img_urls[i]])
    p.start()
    processess.append(p)
    
for process in processess:
    process.join()
"""

t2 = time.perf_counter()

print(f'Finished in {t2-t1} seconds')

In [42]:
import numpy as np

class TrojanGoPlane():
    def __init__(self, board_size, plane_size):
        self.board_width, self.board_height = board_size
        self.num_planes = plane_size
    def name(self):
            return 'trojangoplane'

    def encode(self, game_state):    # <1>
            board_tensor = np.zeros(self.shape())
            print(type(board_tensor))
            #print(board_tensor.shape())
            print(board_tensor)
            #raise NotImplementedError()

    def encode_point(self, point):
            raise NotImplementedError()

    def num_points(self):
            return self.board_width * self.board_height

    def shape(self):
            return self.num_planes, self.board_height, self.board_width

# <1> Encode the input feature (board_size * board_size * num_planes)

def create(board_size, num_planes):
    encoder = TrojanGoPlane(board_size, num_planes)
    encoder.encode("101")

In [43]:
create((5,5), 3)

<class 'numpy.ndarray'>
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [56]:
my_points = [(r, c) for r in range(5) for c in range(5)]
for point in my_points:
    print(point)


(0, 0)
(0, 1)
(0, 2)
(0, 3)
(0, 4)
(1, 0)
(1, 1)
(1, 2)
(1, 3)
(1, 4)
(2, 0)
(2, 1)
(2, 2)
(2, 3)
(2, 4)
(3, 0)
(3, 1)
(3, 2)
(3, 3)
(3, 4)
(4, 0)
(4, 1)
(4, 2)
(4, 3)
(4, 4)


9

In [65]:
import numpy as np
game_state = np.zeros((5,5))
print(game_state)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [81]:
from copy import copy, deepcopy

game_state[2][2] = 1
game_state[3][3] = 2
game_state[1][2] = 1
game_state[2][3] = 2

print("*"*60) 
print(game_state)
print("*"*60) 
#chance Black

    


def convert2to0(game_state):
    board_plane = deepcopy(game_state)
    white_points = [(i,j) for i in range(5) for j in range(5) if game_state[i][j] == 2]
    for row,col in white_points:
        board_plane[row][col] = 0
    return board_plane

def convert2to1and1to0(game_state):
    board_plane = deepcopy(game_state)
    black_points = [(i,j) for i in range(5) for j in range(5) if game_state[i][j] == 1]
    for row,col in black_points:
        board_plane[row][col] = 0
    white_points = [(i,j) for i in range(5) for j in range(5) if game_state[i][j] == 2]
    for row,col in white_points:
        board_plane[row][col] = 1        
    return board_plane
    
print("*"*60)    
print(convert2to0(game_state))
print("*"*60) 
print(convert2to1and1to0(game_state)) 


************************************************************
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 2. 0.]
 [0. 0. 0. 2. 0.]
 [0. 0. 0. 0. 0.]]
************************************************************
************************************************************
[[0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
************************************************************
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [90]:
import numpy as np

plane1 = np.ones((1,5,5))
print(type(plane1))
print(plane1)

print("*"*60)
plane2 = np.ones([1,5,5])
print(type(plane2))
print(plane2)


print("="*60)
plane1 = np.ones((5,5,1))
print(type(plane1))
print(plane1)

print("*"*60)
plane2 = np.ones([5,5,1])
print(type(plane2))
print(plane2)


<class 'numpy.ndarray'>
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
************************************************************
<class 'numpy.ndarray'>
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
<class 'numpy.ndarray'>
[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]
************************************************************
<class 'numpy.ndarray'>
[[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]


In [92]:
"""
Author : Rupesh Kumar
Date   : June 8th 2020

Description : Generate Input features.

"""

import numpy as np
from algos import GlobalConfig


"""
Big Idea for the code written in this file:
===========================================

Assuming 5*5 go board size.

Given: given a board state, generate the input feature stacks/planes (in this case 7*5*5)
Plane[0] = current player (if Black turn then all ones, if white turn then all zeros)

Plane[1] = current player all moves made till now (say ith move) with all ones & others as zeros    (self 1st history)
Plane[2] = current player all moves made till (i-1)th move with all ones & others as zeros          (self 2nd history)
Plane[3] = current player all moves made till (i-2)th move with all ones & others as zeros          (self 3rd history)

Plane[4] = opposotion player all moves made till now (say jth move) with all ones & others as zeros (opp 1st history)
Plane[5] = opposotion player all moves made till (j-1)th move with all ones & others as zeros       (opp 2nd history)
Plane[6] = opposotion player all moves made till (j-2)th move with all ones & others as zeros       (opp 3rd history)

NOTE: if (i-n)th or (j-n)th move doesn't exist then the plane will have all zeros.
"""

"""
Feature name            num of planes   Description
Current Player          1               Player stone / opponent stone / empty
Current 8 history       8               Cuurent Player 8 history states
Opposition 8 history    8               Opposition player 8 history states
"""


FEATURE_OFFSETS = {
    "current_player": 0,    # <1>
    "base_self_history": 1, # <2>
    "base_opp_history": 1 + int((num_planes-1)/2) # <3>
}

# <1> Plane[0]
# <2> Plane [1,2,3,4,5,6,7,8] or [1,2,3]
# <3> Plane [9, 10, 11, 12, 13, 14, 15, 16] or [4,5,6] (num_planes is coming from global config file)

def offset(feature):
    return FEATURE_OFFSETS[feature]




class TrojanGoPlane(Encoder):
        def __init__(self, board_size, plane_size):
            self.board_width, self.board_height = board_size
            self.num_planes = plane_size
            
        def name(self):
            return 'trojangoplane'

        # Need to define Point, Player, game_state (previous game_state info, 1 black, 2 white and 0 for blank point)
        def encode(self, game_state):    # <1> 
            board_tensor = np.zeros(self.shape())  # (17*19*19)

            plane_history = 1
            opp = True
            self = False
            iter_base_opp = 0
            iter_base_self = 0
            
            while game_state and plane_history <= (num_planes - 1):
                if (opp):
                    # from current player point of view, current game_state is first history
                    # game_state of opposition. So, it should go in opposition base plane.
                    # 2->1 & 1->0 (if game_state.current_player == Player.black),
                    # and 2->0(if game_state.current_player == Player.white)
                    
                    if game_state.current_player == Player.black:
                       board_plane = convert2to1and1to0(game_state)
                    else:
                       board_plane = convert2to0(game_state)                 
                    

                    board_tensor[offset("base_opp_history") + iter_base_opp] = board_plane
                    plane_history += 1
                    iter_base_opp += 1
                    opp = False
                    self = True
                    game_state = game_state.previous
                            
                if (self):
                    # 2->0 (if game_state.current_player == Player.black),
                    # and 2->1 & 1->0 (if game_state.current_player == Player.white)
                    
                    if game_state.current_player == Player.black:
                       board_plane = convert2to0(game_state)
                    else:
                       board_plane = convert2to1and1to0(game_state)
                       
                    board_tensor[offset("base_self_history") + iter_base_self] = board_plane
                    plane_history += 1
                    iter_base_self+= 1
                    opp = True
                    self = False
                    game_state = game_state.previous                 
            
           
            if game_state.current_player == Player.black:
                board_tensor[offset("current_player")] = np.ones([1, self.board_width, self.board_width])
            if game_state.current_player == Player.white:
                board_tensor[offset("current_player")] = np.zeros([1, self.board_width, self.board_width])                  

            
        def encode_point(self, point):
            raise NotImplementedError()

        def num_points(self):
            return self.board_width * self.board_height

        def shape(self):
            return self.num_planes, self.board_height, self.board_width

# <1> Encode the input feature (board_size * board_size * num_planes)

def create(board_size, num_planes):
    return TrojanGoPlane(board_size, num_planes)

                


ModuleNotFoundError: No module named 'algos'